# Generated by Django 4.2.1 on 2023-06-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_nullblankdemo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nullblankdemo',
            name='id',
        ),
        migrations.AddField(
            model_name='nullblankdemo',
            name='custom_id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
