# Generated by Django 4.2.1 on 2023-06-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_department_created_on_department_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
    ]
