# Generated by Django 4.2.1 on 2023-06-15 17:54

from django.db import migrations
from django.utils.text import slugify


def add_slugs(apps, schema_editor):

    Department = apps.get_model('web', 'Department')
    departments = Department.objects.all()
    for department in departments:
        department.slug = slugify(department.name)
    Department.objects.bulk_update(departments, ['slug'])


def remove_slugs(apps, schema_editor):
    department = apps.get_model('web', 'Department')
    departments = department.objects.all()
    for department in departments:
        department.slug = None
    department.objects.bulk_update(departments, ['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_department_slug'),
    ]

    operations = [
        migrations.RunPython(add_slugs, remove_slugs),
    ]
