# Generated by Django 4.2.2 on 2023-06-29 16:51

import Models_demos.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20230615_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='age',
            field=models.IntegerField(validators=[Models_demos.web.models.above_eighteen]),
        ),
    ]
